trigger:
- master
- release/*
pr:
- master
- release/*

jobs:
- job: windows
  displayName: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    matrix:
      Win32:
        BuildArch: 'Win32'
        VcpkgTargetTriplet: 'x86-windows-static'
      Win64:
        BuildArch: 'x64'
        VcpkgTargetTriplet: 'x64-windows-static'

  steps:
  - template: azure-pipelines/templates/ci-git-rebase.yml
  - template: azure-pipelines/templates/windows-dependencies.yml
  - template: azure-pipelines/templates/ci-opengfx.yml
    parameters:
      SharedFolder: C:/Users/Public/Documents/OpenTTD
  - template: azure-pipelines/templates/windows-build.yml
    parameters:
      BuildArch: $(BuildArch)
      VcpkgTargetTriplet: $(VcpkgTargetTriplet)
      BuildConfiguration: 'Debug'
  - task: VSBuild@1
    displayName: 'Prepare regression files'
    inputs:
      solution: build/regression_files.vcxproj
      configuration: 'Debug'
  - task: VSBuild@1
    displayName: 'Test'
    inputs:
      solution: build/RUN_TESTS.vcxproj
      configuration: 'Debug'


- job: linux
  displayName: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      linux-amd64-clang-3.9:
        Tag: 'linux-amd64-clang-3.9'
      linux-amd64-gcc-6:
        Tag: 'linux-amd64-gcc-6'
      linux-i386-gcc-6:
        Tag: 'linux-i386-gcc-6'

  steps:
  - template: azure-pipelines/templates/ci-git-rebase.yml
  # The dockers already have the dependencies installed
  - template: azure-pipelines/templates/ci-opengfx.yml
    parameters:
      SharedFolder: /usr/local/share/games/openttd
      PrefixCommand: sudo
  - template: azure-pipelines/templates/linux-build.yml
    parameters:
      Image: compile-farm-ci
      Tag: $(Tag)

- job: macos
  displayName: 'MacOS'
  pool:
    vmImage: 'macOS-10.14'

  variables:
    MACOSX_DEPLOYMENT_TARGET: 10.9

  steps:
  - template: azure-pipelines/templates/ci-git-rebase.yml
  - template: azure-pipelines/templates/osx-dependencies.yml
  - template: azure-pipelines/templates/ci-opengfx.yml
    parameters:
      SharedFolder: /Library/Application Support/OpenTTD
      PrefixCommand: sudo
  - template: azure-pipelines/templates/osx-build.yml
  - script: |
      set -ex

      cd build
      CTEST_OUTPUT_ON_FAILURE=1 make test
    displayName: 'Test'
