trigger:
- master
pr:
- master

jobs:
- job: windows
  displayName: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'

  strategy:
    matrix:
      Win32:
        BuildPlatform: 'Win32'
      Win64:
        BuildPlatform: 'x64'

  steps:
  - template: azure-pipelines/ci-git-rebase.yml
  - template: azure-pipelines/windows-dependencies.yml
  - template: azure-pipelines/ci-opengfx.yml
  - template: azure-pipelines/windows-build.yml
    parameters:
      BuildPlatform: $(BuildPlatform)
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
      cd projects
      call regression.bat
    displayName: 'Test'

- job: linux
  displayName: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      commit-checker: {}
      linux-amd64-clang-3.8: {}
      linux-amd64-gcc-6: {}
      linux-i386-gcc-6: {}

  steps:
  - template: azure-pipelines/ci-git-rebase.yml
  - template: azure-pipelines/linux-build.yml
    parameters:
      BaseImage: compile-farm-ci

- job: macos
  displayName: 'MacOS'
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - template: azure-pipelines/ci-git-rebase.yml
  - template: azure-pipelines/osx-dependencies.yml
  - template: azure-pipelines/ci-opengfx.yml
  - template: azure-pipelines/osx-build.yml
  - script: 'make regression'
    displayName: 'Test'
