add_library(ZLIB::ZLIB INTERFACE IMPORTED)
set_target_properties(ZLIB::ZLIB PROPERTIES
        INTERFACE_COMPILE_OPTIONS "-sUSE_ZLIB=1"
        INTERFACE_LINK_LIBRARIES "-sUSE_ZLIB=1"
)

set(ZLIB_FOUND on)
