add_library(PNG::PNG INTERFACE IMPORTED)
set_target_properties(PNG::PNG PROPERTIES
        INTERFACE_COMPILE_OPTIONS "-sUSE_LIBPNG=1"
        INTERFACE_LINK_LIBRARIES "-sUSE_LIBPNG=1"
)

set(PNG_FOUND on)
