; This file is part of OpenTTD.
; OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
; OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
; See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <http://www.gnu.org/licenses/>.
;

; Pathfinding settings as stored in the main configuration file ("openttd.cfg")
; and in the savegame PATS chunk.

[pre-amble]
bool _old_pf_ship_use_yapf; ///< Use YAPF for ships (setting from old savegames)
bool _old_pf_road_use_yapf; ///< Use YAPF for road (setting from old savegames)
bool _old_pf_rail_use_yapf; ///< Use YAPF for rail (setting from old savegames)
static void InvalidateShipPathCache(int32 new_value);

static const SettingVariant _pathfinding_settings_table[] = {
[post-amble]
};
[templates]
SDT_BOOL   =   SDT_BOOL(GameSettings, $var,        $flags, $def,                              $str, $strhelp, $strval, $pre_cb, $post_cb, $from, $to,        $cat, $extra, $startup),
SDT_VAR    =    SDT_VAR(GameSettings, $var, $type, $flags, $def,       $min, $max, $interval, $str, $strhelp, $strval, $pre_cb, $post_cb, $from, $to,        $cat, $extra, $startup),
SDTG_BOOL  =  SDTG_BOOL($name,        $flags, $var, $def,                               $str, $strhelp, $strval, $pre_cb, $post_cb, $from, $to, $cat, $extra, $startup),

[validation]
SDT_VAR = static_assert($max <= MAX_$type, "Maximum value for GameSettings.$var exceeds storage size");

[defaults]
flags    = SF_NONE
interval = 0
str      = STR_NULL
strhelp  = STR_CONFIG_SETTING_NO_EXPLANATION_AVAILABLE_HELPTEXT
strval   = STR_NULL
pre_cb   = nullptr
post_cb  = nullptr
load     = nullptr
from     = SL_MIN_VERSION
to       = SL_MAX_VERSION
cat      = SC_ADVANCED
extra    = 0
startup  = false


[SDT_BOOL]
var      = pf.forbid_90_deg
def      = false
str      = STR_CONFIG_SETTING_FORBID_90_DEG
strhelp  = STR_CONFIG_SETTING_FORBID_90_DEG_HELPTEXT
post_cb  = InvalidateShipPathCache
cat      = SC_EXPERT

[SDT_BOOL]
var      = pf.roadveh_queue
def      = true
cat      = SC_EXPERT

[SDTG_BOOL]
name      = ""pf.yapf.ship_use_yapf""
var      = _old_pf_ship_use_yapf
from     = SLV_28
to       = SLV_87
def      = false
cat      = SC_EXPERT

[SDTG_BOOL]
name      = ""pf.yapf.road_use_yapf""
var      = _old_pf_road_use_yapf
from     = SLV_28
to       = SLV_87
def      = true
cat      = SC_EXPERT

[SDTG_BOOL]
name      = ""pf.yapf.rail_use_yapf""
var      = _old_pf_rail_use_yapf
from     = SLV_28
to       = SLV_87
def      = true
cat      = SC_EXPERT

[SDT_VAR]
var      = pf.pathfinder_for_trains
type     = SLE_UINT8
from     = SLV_87
flags    = SF_GUI_DROPDOWN
def      = 2
min      = 1
max      = 2
interval = 1
str      = STR_CONFIG_SETTING_PATHFINDER_FOR_TRAINS
strhelp  = STR_CONFIG_SETTING_PATHFINDER_FOR_TRAINS_HELPTEXT
strval   = STR_CONFIG_SETTING_PATHFINDER_NPF
cat      = SC_EXPERT

[SDT_VAR]
var      = pf.pathfinder_for_roadvehs
type     = SLE_UINT8
from     = SLV_87
flags    = SF_GUI_DROPDOWN
def      = 2
min      = 1
max      = 2
interval = 1
str      = STR_CONFIG_SETTING_PATHFINDER_FOR_ROAD_VEHICLES
strhelp  = STR_CONFIG_SETTING_PATHFINDER_FOR_ROAD_VEHICLES_HELPTEXT
strval   = STR_CONFIG_SETTING_PATHFINDER_NPF
cat      = SC_EXPERT

[SDT_VAR]
var      = pf.pathfinder_for_ships
type     = SLE_UINT8
from     = SLV_87
flags    = SF_GUI_DROPDOWN
def      = 2
min      = 1
max      = 2
interval = 1
str      = STR_CONFIG_SETTING_PATHFINDER_FOR_SHIPS
strhelp  = STR_CONFIG_SETTING_PATHFINDER_FOR_SHIPS_HELPTEXT
strval   = STR_CONFIG_SETTING_PATHFINDER_NPF
post_cb  = InvalidateShipPathCache
cat      = SC_EXPERT

[SDT_BOOL]
var      = pf.reverse_at_signals
from     = SLV_159
def      = false
str      = STR_CONFIG_SETTING_REVERSE_AT_SIGNALS
strhelp  = STR_CONFIG_SETTING_REVERSE_AT_SIGNALS_HELPTEXT

[SDT_VAR]
var      = pf.wait_oneway_signal
type     = SLE_UINT8
def      = 15
min      = 2
max      = 255
cat      = SC_EXPERT

[SDT_VAR]
var      = pf.wait_twoway_signal
type     = SLE_UINT8
def      = 41
min      = 2
max      = 255
cat      = SC_EXPERT

[SDT_VAR]
var      = pf.wait_for_pbs_path
type     = SLE_UINT8
from     = SLV_100
def      = 30
min      = 2
max      = 255
cat      = SC_EXPERT

[SDT_BOOL]
var      = pf.reserve_paths
from     = SLV_100
def      = false
cat      = SC_EXPERT

[SDT_VAR]
var      = pf.path_backoff_interval
type     = SLE_UINT8
from     = SLV_100
def      = 20
min      = 1
max      = 255
cat      = SC_EXPERT
