name: Bug Report
description: Found a bug in OpenTTD?
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Version of OpenTTD
      description: Fill in below what version of OpenTTD you are using, including your OS.
      placeholder: ex. 1.11.2, Windows 10
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      description: Describe in a few words what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      description: Describe in a few words what actually happens.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: As detailed as possible, please tell us how we can reproduce this. Feel free to attach a savegame (zip it first) to make it more clear.
      placeholder: |
        1. Loaded the attached savegame.
        2. Click on the button left of that other icon.
        3. The window doesn't open.
    validations:
      required: true
