#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

FILES="trg1r.grf trgcr.grf trghr.grf trgir.grf trgtr.grf sample.cat"
DATADIR=/usr/share/games/openttd/data

MISSING="No"
for FILE in $FILES; do
	# Check if all the files needed are here.
	if [ ! -e $DATADIR/$FILE ]; then
		MISSING="Yes"
		break
	fi;
done

if [ $MISSING = "Yes" ]; then
	db_input high openttd/datafiles || true
	db_go
fi
