name: AppImage CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pack:
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libfontconfig-dev \
            libicu-dev \
            liblzma-dev \
            liblzo2-dev \
            libsdl1.2-dev \
            libsdl2-dev \
            libxdg-basedir-dev \
            zlib1g-dev \
            # EOF

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
          make -j`nproc`
          make install -j$(nproc) DESTDIR=AppDir

      - name: Create AppImage
        uses: AppImageCrafters/build-appimage-action@master
        env:
            BUILDER_WORKDIR: build
            BUILDER_VERSION: 0.7.3
        with:
          recipe: ../os/linux/appimage-builder.yml

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: ./build/*.AppImage
