name: Preview publish

on:
  workflow_run:
    workflows:
    - Preview
    types:
    - completed

jobs:
  preview:
    name: Publish preview

    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
    - name: Create deployment
      id: deployment
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        https://api.github.com/repos/${{ github.repository }}/deployments \
        -d '{"ref":"${{ github.event.workflow_run.head_sha }}","environment":"preview","required_contexts":[]}' \
        | jq --raw-output0 '"url=\(.statuses_url)"' >> $GITHUB_OUTPUT

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{github.event.workflow_run.id }}

    - name: Get PR number
      id: pr
      run: |
        echo "number=$(cat pr/number)" >> $GITHUB_OUTPUT

    - name: Publish preview
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.PREVIEW_CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.PREVIEW_CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy public --project-name=${{ vars.PREVIEW_CLOUDFLARE_PROJECT_NAME }} --branch pr${{ steps.pr.outputs.number }}

    - name: Update deployment
      if: always()
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2026-03-10" \
        ${{ steps.deployment.outputs.url }} \
        -d '{"state":"${{ job.status }}","log_url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}","environment_url":"https://preview.openttd.org/pr${{ steps.pr.outputs.number }}/"}'
