parameters:
  SharedFolder: '/usr/local/share/games/openttd'
  PrefixCommand: ''

steps:
- bash: |
    set -ex
    ${{ parameters.PrefixCommand }} mkdir -p "${{ parameters.SharedFolder }}/baseset"
    cd "${{ parameters.SharedFolder }}/baseset"
    ${{ parameters.PrefixCommand }} curl -L https://cdn.openttd.org/opengfx-releases/0.6.0/opengfx-0.6.0-all.zip -o opengfx-all.zip
    ${{ parameters.PrefixCommand }} unzip opengfx-all.zip
    ${{ parameters.PrefixCommand }} rm -f opengfx-all.zip
  displayName: 'Install OpenGFX'
