# Fetch the source tarball as prepared by an earlier job. In there is the
# version predefined. This ensures we are all going to compile the same
# source with the same version.

steps:
- checkout: none
- task: DownloadBuildArtifacts@0
  displayName: 'Download source'
  inputs:
    downloadType: specific
    itemPattern: 'bundles/openttd-*-source.tar.xz'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
- bash: tar --xz -xf ../a/bundles/openttd-*-source.tar.xz --strip-components=1
  displayName: 'Extracting source'
- bash: |
    set -e
    VERSION=$(cat .version)
    echo "${VERSION}"
    echo "##vso[build.updatebuildnumber]${VERSION}"
  displayName: 'Change BuildNumber to version'
