parameters:
  CalculateChecksums: true

steps:
- ${{ if eq(parameters.CalculateChecksums, true) }}:
  - bash: |
      set -ex
      cd build/bundles

      # CPack generates sha256, but with a slightly different name than
      # our own convention. Also, because we rename files, the content
      # might be out of date. To be safe, we remove it and replace it
      # with our own version.
      rm -f *.sha256

      for i in $(ls); do
        openssl dgst -r -md5 -hex $i > $i.md5sum
        openssl dgst -r -sha1 -hex $i > $i.sha1sum
        openssl dgst -r -sha256 -hex $i > $i.sha256sum
      done
    displayName: 'Calculate checksums'
- task: PublishBuildArtifacts@1
  displayName: 'Publish bundles'
  inputs:
    PathtoPublish: build/bundles/
    ArtifactName: bundles
