steps:
- bash: |
    set -ex

    curl -L https://github.com/OpenTTD/CompileFarm/releases/download/latest/windows-dependencies.zip > windows-dependencies.zip
    unzip windows-dependencies.zip
    rm -f windows-dependencies.zip

    mv windows-dependencies/installed /c/vcpkg/
    rm -rf windows-dependencies
  displayName: 'Install dependencies'
  workingDirectory: $(Build.ArtifactStagingDirectory)
- script: c:\vcpkg\vcpkg.exe integrate install
  displayName: 'Integrate vcpkg'
