parameters:
  BuildArch: ''
  VcpkgTargetTriplet: ''
  BuildConfiguration: ''
  OptionUseNSIS: 'OFF'

steps:
- task: CMake@1
  displayName: 'Configure'
  inputs:
    cmakeArgs: '.. -G "Visual Studio 15 2017" -A ${{ parameters.BuildArch }} -DCMAKE_TOOLCHAIN_FILE="c:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="${{ parameters.VcpkgTargetTriplet }}" -DOPTION_USE_NSIS="${{ parameters.OptionUseNSIS }}"'
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: build/openttd.vcxproj
    configuration: ${{ parameters.BuildConfiguration }}
    maximumCpuCount: true
